version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: coworking_postgres
    environment:
      POSTGRES_DB: coworking_db
      POSTGRES_USER: coworking_user
      POSTGRES_PASSWORD: coworking_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: